language: java
jdk:
  - openjdk7

# whitelist
branches:
  only:
    - master

env:
  global:
    - secure: "h1TgWcx8cR0c3GQ5T/p25+rYkhoMcqNSDiXX+kRlb58b0KHThlOnMMap2M460H+o1AD0fpN7VJhvspVnCJdoEaEq4zsdj7WfTvKNxFly+YCcWF7AsxNejXPm8AwHZABF8SNB6tnWpRRwK6gxuUoeUINFci0tryBuqx5N1X12s/w="
    - secure: "VltfieaVd+SMhtpe/JzBVGvevQwx6Hn0DXTZAHFSDZ3rjuolsOjCtez9LjhLN3uQp3225yrHtasDtHFyrkiPLWAH2A4XPj1Fo4xH0IYsM7A6xBZAcAJX8tvHwAXY2nhDAlhtjzKSQyev3pcBSbsBer7gns/1EDETVhkgPTKN9EM="

before_install:
  - sudo apt-get update -qq
  - git clone --depth=50 --branch=master git://github.com/GraphWalker/graphwalker-project.git ../graphwalker-project
  - ../graphwalker-project/tools/clone.sh
  - ../graphwalker-project/tools/build.sh

install:
  - mvn -q deploy --settings ../graphwalker-project/deploy.xml
